# Generated by Django 3.2 on 2021-04-26 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.IntegerField()),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ToBePaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tobe_date', models.DateTimeField()),
                ('tobe_for', models.CharField(max_length=100)),
                ('tobe_work', models.CharField(max_length=300)),
                ('tobe_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tobe_Sure', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateTimeField()),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_description', models.CharField(max_length=350)),
                ('income_note', models.CharField(max_length=350)),
                ('income_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymoney.moneyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expence_date', models.DateTimeField()),
                ('expence_catagory', models.CharField(max_length=100)),
                ('expence_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expence_description', models.CharField(max_length=350)),
                ('expence_note', models.CharField(max_length=350)),
                ('expence_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymoney.moneyaccount')),
            ],
        ),
    ]
