# Generated by Django 3.2 on 2021-04-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymoney', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expence',
            new_name='Expense',
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Expense'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Income'},
        ),
        migrations.AlterModelOptions(
            name='moneyaccount',
            options={'verbose_name': 'Account'},
        ),
        migrations.AlterModelOptions(
            name='tobepaid',
            options={'verbose_name': 'To Be Paid', 'verbose_name_plural': 'To Be Paid'},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='expence_account',
            new_name='expense_account',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='expence_amount',
            new_name='expense_amount',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='expence_catagory',
            new_name='expense_category',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='expence_date',
            new_name='expense_date',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='expence_description',
            new_name='expense_description',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='expence_note',
            new_name='expense_note',
        ),
        migrations.RenameField(
            model_name='tobepaid',
            old_name='tobe_for',
            new_name='tobe_from',
        ),
    ]
