# Generated by Django 3.2 on 2021-04-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoney', '0003_alter_moneyaccount_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_note',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='moneyaccount',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
