# Generated by Django 3.2 on 2021-04-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymoney', '0004_auto_20210426_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymoney.moneyaccount'),
        ),
    ]
