# Generated by Django 3.2 on 2021-05-04 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymoney', '0006_auto_20210504_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField()),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_reason', models.CharField(max_length=300)),
                ('transfer_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='mymoney.moneyaccount')),
                ('transfer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='mymoney.moneyaccount')),
            ],
            options={
                'verbose_name': 'Transfers',
            },
        ),
    ]
