# Generated by Django 3.2 on 2021-05-04 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymoney', '0008_alter_transfers_transfer_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymoney.moneyaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='income_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymoney.moneyaccount'),
            preserve_default=False,
        ),
    ]
